*;
*MEAN-MAX-MIN-MEDIAN-MIDRANGE AND ROBUST ESTIMATES;
*;
label IMP_LOG_REP_high = 'Imputed: Transformed: Replacement: high';
IMP_LOG_REP_high = LOG_REP_high;
if missing(LOG_REP_high) then IMP_LOG_REP_high = 0.9110992144;
label IMP_LOG_REP_low = 'Imputed: Transformed: Replacement: low';
IMP_LOG_REP_low = LOG_REP_low;
if missing(LOG_REP_low) then IMP_LOG_REP_low = 0.900448506;
label IMP_LOG_REP_open = 'Imputed: Transformed: Replacement: open';
IMP_LOG_REP_open = LOG_REP_open;
if missing(LOG_REP_open) then IMP_LOG_REP_open = 0.9045999876;
*;
*INDICATOR VARIABLES;
*;
label M_LOG_REP_high = "Imputation Indicator for LOG_REP_high";
if missing(LOG_REP_high) then M_LOG_REP_high = 1;
else M_LOG_REP_high= 0;
label M_LOG_REP_low = "Imputation Indicator for LOG_REP_low";
if missing(LOG_REP_low) then M_LOG_REP_low = 1;
else M_LOG_REP_low= 0;
label M_LOG_REP_open = "Imputation Indicator for LOG_REP_open";
if missing(LOG_REP_open) then M_LOG_REP_open = 1;
else M_LOG_REP_open= 0;
